#Switches A[3:0] y B[3:0]
set_property PACKAGE_PIN V17 [get_ports {B[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property PACKAGE_PIN V16 [get_ports {B[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property PACKAGE_PIN W16 [get_ports {B[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property PACKAGE_PIN W17 [get_ports {B[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property PACKAGE_PIN W2 [get_ports {A[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property PACKAGE_PIN U1 [get_ports {A[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property PACKAGE_PIN T1 [get_ports {A[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property PACKAGE_PIN R2 [get_ports {A[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
	
#Segmentos display
set_property PACKAGE_PIN W7 [get_ports {a_seg}]
	set_property IOSTANDARD LVCMOS33 [get_ports {a_seg}]
set_property PACKAGE_PIN W6 [get_ports {b_seg}]
	set_property IOSTANDARD LVCMOS33 [get_ports {b_seg}]
set_property PACKAGE_PIN U8 [get_ports {c_seg}]
	set_property IOSTANDARD LVCMOS33 [get_ports {c_seg}]
set_property PACKAGE_PIN V8 [get_ports {d_seg}]
	set_property IOSTANDARD LVCMOS33 [get_ports {d_seg}]
set_property PACKAGE_PIN U5 [get_ports {e_seg}]
	set_property IOSTANDARD LVCMOS33 [get_ports {e_seg}]
set_property PACKAGE_PIN V5 [get_ports {f_seg}]
	set_property IOSTANDARD LVCMOS33 [get_ports {f_seg}]
set_property PACKAGE_PIN U7 [get_ports {g_seg}]
    set_property IOSTANDARD LVCMOS33 [get_ports {g_seg}]
    
#Transistores del display
set_property PACKAGE_PIN U2 [get_ports {T[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {T[0]}]
set_property PACKAGE_PIN U4 [get_ports {T[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {T[1]}]
set_property PACKAGE_PIN V4 [get_ports {T[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {T[2]}]
set_property PACKAGE_PIN W4 [get_ports {T[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {T[3]}]
	
#LED cout
set_property PACKAGE_PIN U16 [get_ports {cout}]
	set_property IOSTANDARD LVCMOS33 [get_ports {cout}]